# Generated by Django 4.0.3 on 2022-05-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='top_candidates',
        ),
    ]
